### ISSUE TITLE
Movie App Dosyaları

### ISSUE THREAD

**Issue by abdulkadirbak** [meseven/react-redux-egitim-seti#4]
Movie App dersinizde gösterdiğiniz repo nun dosyalarını bulamadım ama nerdeydi tam olarak readme dosyasında link vermişsiniz ama çalışmıyor.

**Comment by serhat-zirhli** [comment]
Prod branch üzerinden ulaşabilirsin.
https://github.com/meseven/react-redux-egitim-seti/tree/prod/react-redux-movie-app/backend
